export const definitions: Record<string, string> = {
  'UCP': 'Universal Commerce Protocol - A standard way for different shopping systems to talk to each other.',
  'ACP': 'Agentic Commerce Protocol - A set of rules that allows AI agents to browse and buy products on your behalf.',
  'MCP': 'Model Context Protocol - A standard that helps AI models (like ChatGPT) access and understand your data safely.',
  'AP2': 'Agent Protocol 2 - An advanced communication standard for autonomous AI shopping assistants.',
  'MCP app': 'A specialized application built using the Model Context Protocol to provide specific data or tools to AI models.',
  'Generative Discovery': 'When people use AI like ChatGPT or Perplexity to find products instead of using a traditional search engine like Google.',
  'Personal AI Shoppers': 'AI assistants that learn your preferences and find the best products for you automatically.',
  'Agent-to-Agent Negotiation': 'When your AI assistant talks directly to a store\'s AI to get you the best price or deal.',
  'Agentic Commerce': 'Shopping where AI agents handle the discovery, evaluation, and even the purchase of products.',
  'Commerce Platform': 'The software used to power an online store (e.g., Shopify, BigCommerce).',
  'AI Channel': 'A specific way or place where customers use AI to interact with your brand.',
  'Customer Acquisition Cost': 'The total cost of winning a customer to purchase a product or service.',
  'Conversion Rate': 'The percentage of visitors to your website who complete a desired goal (like making a purchase).',
  'Future-proof': 'Designing something so it continues to be useful and compatible even as technology changes in the future.',
  'Brand Innovation Leadership': 'Being at the forefront of new technology to stay ahead of competitors.',
  'Semantic Search': 'A search technique that understands the intent and meaning behind a search query, rather than just matching keywords.',
  'AI Personalization': 'Using AI to tailor the shopping experience to each individual customer\'s behavior and preferences.',
  'Agentic Ready': 'When a website is technically prepared to be understood and used by AI shopping agents.',
  'Headless': 'A type of website architecture where the front-end display is separate from the back-end commerce engine, allowing for more flexibility.',
  'API': 'Application Programming Interface - A way for two or more computer programs to communicate with each other.',
  'Vector': 'In AI, a way to represent data (like products or text) as numbers so the AI can easily find similar items.',
  'Audit': 'A thorough examination and evaluation of a website\'s technical capabilities and readiness.',
  'llms.txt': 'A standard text file that provides AI models with concise, high-quality information about a website to improve their understanding.',
  'llms.text': 'An alternative name for the llms.txt file, used to provide context about a website to AI models.',
  'OpenCart': 'A popular open-source eCommerce platform known for its user-friendly interface and extensive extension marketplace.',
  'PrestaShop': 'A flexible and scalable open-source eCommerce solution used by hundreds of thousands of merchants worldwide.',
  'Sitecore CMS': 'An enterprise-level content management system that provides powerful personalization and marketing automation tools.',
  'Adobe CQ (AEM)': 'Adobe Experience Manager, a comprehensive content management solution for building websites, mobile apps, and forms.',
  'WeltPixel': 'A specialized agency and extension provider that focuses on enhancing Magento and Adobe Commerce stores.',
  'AVADA Commerce': 'An eCommerce marketing automation platform that helps merchants grow their business through email marketing and more.',
  'Demandware': 'The original name for Salesforce Commerce Cloud, a leading enterprise cloud commerce platform.'
};
